### ISSUE TITLE
Getting Split data

### ISSUE THREAD

**Issue by bjorntheart** [hozn/stravalib#76] opened 2016-07-07 12:08 UTC
The `split_metric` and `split_standard` collections on my activity returns `None`. I don't know if I understand the splits entirely, but I think it represents the Splits in Strava next to the map. In which case, for this specific workout activity, I should have split results as a collection on the Activity model, but I get `None`
<img width="243" alt="screen shot 2016-07-07 at 14 06 08" src="https://cloud.githubusercontent.com/assets/53244/16652620/03ee4474-444c-11e6-8ca7-e09b158b4573.png">

**Comment by hozn** [comment] 2016-07-10 18:08
Sorry, I haven't had a chance to look at this yet.  As all my usage has been cycling-specific, it wouldn't surprise me if there's just a bug in this feature.  When you make the query do you see debug logs indicating the Strava API URL being hit, etc. ?

**Comment by hozn** [comment] 2016-07-10 18:12
Note that those attributes are only expected to be available for the DETAILED view (i.e. when the activity is being fetched on behalf of the authorized user -- not available for activities of auth user's friends / leaderboards, etc.)

**Comment by bjorntheart** [comment] 2016-07-11 15:24
@hozn I authenticate as myself with the 'view_private' scope, so I should be able to see the splits, right? I am not sure if I've correctly configured the logging, but I've set the following:

```
app.debug = True
logging.basicConfig()
```

and don't see any Strava API URL in the shell output logs

I have to functions that just dumps some info:

```
def dump_athlete():
    athlete = client.get_athlete()
    print repr(athlete)

def dump_splits():
    now = datetime.datetime.utcnow()
    week_start = now - datetime.timedelta(days=now.weekday())
    week_end = week_start + datetime.timedelta(days=6)

    activities = client.get_activities(before=week_end, after=week_start)
    results = list(activities)
    for activity in results:
        print activity.splits_metric
        print activity.splits_standard
```

**Comment by hozn** [comment] 2016-07-11 15:29
Ok -- try:

```python
logging.basicConfig(level=logging.DEBUG)
```

I will record a running activity which should have some splits and make sure this shows up as expected.  I see it in the sample activity file that is checked in, but that doesn't mean we have unit tests validating that specific feature (I will add once I get to the bottom of this).

**Comment by bjorntheart** [comment] 2016-07-12 15:29
I've enabled debugging and this is what I get:

```
INFO:stravalib.protocol.ApiV3:GET u'https://www.strava.com/api/v3/athlete/activities' with params {'per_page': 200, 'after': 1468250409, 'page': 1, 'before': 1468768809}
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/v3/athlete/activities?access_token=some_token&per_page=200&after=1468250409&page=1&before=1468768809 HTTP/1.1" 200 22
DEBUG:stravalib.client.BatchedResultsIterator:Requested page 1 (got: 0 items)
```

I definitely have done activities within the past 14 days. 0 items returned for page 1

**Comment by hozn** [comment] 2016-12-04 02:32
Ok, the good news is that I can't reproduce any problems here; splits are working well for me. So either this has been fixed by strava or by side effect of other fixes here.

**Closed by hozn** 2016-12-04 02:32 UTC
